import { Book, ZoneInfo, CatalogFilterState } from "../types/catalog.types"

export const INITIAL_FILTERS: CatalogFilterState = {
  searchQuery: "",
  jenjang: "semua",
  kategori: "semua",
  rak: "semua",
  status: "semua",
  format: "semua",
  tahun: "semua",
}

export const TOPIC_FILTERS = [
  { label: "Semua Koleksi", filter: { searchQuery: "", jenjang: "semua", kategori: "semua", rak: "semua" } as Partial<CatalogFilterState> },
  { label: "Kitab & Fiqih Islam", filter: { searchQuery: "Fiqih", jenjang: "semua", kategori: "agama", rak: "rak-a" } as Partial<CatalogFilterState> },
  { label: "Buku Pelajaran MI (Tematik)", filter: { searchQuery: "Tematik", jenjang: "mi", kategori: "tematik", rak: "rak-b" } as Partial<CatalogFilterState> },
  { label: "Buku Pelajaran MTs", filter: { searchQuery: "MTs", jenjang: "mts", kategori: "semua", rak: "semua" } as Partial<CatalogFilterState> },
  { label: "Kamus Bahasa Arab & Inggris", filter: { searchQuery: "Kamus", jenjang: "semua", kategori: "bahasa", rak: "rak-e" } as Partial<CatalogFilterState> },
  { label: "Sastra & Cerita 25 Nabi", filter: { searchQuery: "Nabi", jenjang: "semua", kategori: "sastra", rak: "rak-d" } as Partial<CatalogFilterState> },
  { label: "Ensiklopedia Sains & Teknologi", filter: { searchQuery: "IPA", jenjang: "semua", kategori: "sains", rak: "rak-c" } as Partial<CatalogFilterState> },
]

export const MOCK_BOOKS: Book[] = [
  {
    id: "1",
    title: "Fiqih Ibadah Praktis MTs",
    callNumber: "BK-AGM-0182",
    author: "Drs. H. Ahmad Muhaimin",
    publisher: "Kemenag RI",
    year: "2023",
    synopsis: "Panduan fiqih praktis mencakup thaharah, shalat fardhu dan sunnah, zakat, puasa, dan manasik haji sesuai kurikulum madrasah.",
    badgeLabel: "MTs • Fiqih Madrasah",
    location: "📍 Rak A1 - Baris Ke-2 (Sektor Keagamaan)",
    rack: "rak-a",
    jenjang: "mts",
    kategori: "agama",
    status: "tersedia",
    format: "buku-cetak",
    tahunRange: "2023-2024",
    availableCopies: 12,
    totalCopies: 15,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuADpbib5TGUwdmqjgZFG2h8acHvT4YpO3HX9f-T-K3uEuPSwnqH6WBW3UHynQhrGClLhsrKl6L5sahJvHGnOP0LHJ_1jcuVeDdW6ziGPAKWcsQBoeW_f42AL1-g-OeNX_9JtiuiIJs5F-YrjS55HhcBeIS8NgQOaPH9n_HpzY-PBafIE1aHt0XWWuPhX397btLBHqdzcd34Pz5v9xMXPfvO72V8uWMDd7w9PB46w48NFcCJe8egd1rV",
  },
  {
    id: "2",
    title: "Tematik Terpadu 5B: Udara Bersih bagi Kesehatan",
    callNumber: "BK-TMT-0419",
    author: "Tim Penulis Kemendikbud",
    publisher: "Balai Pustaka",
    year: "2022",
    synopsis: "Buku tematik kelas 5 Tema 2 membahas pernapasan manusia dan hewan, udara bersih di lingkungan, dan cara menjaga kesehatan paru-paru.",
    badgeLabel: "MI • Tematik Kelas 5",
    location: "📍 Rak B1 - Baris Ke-1 (Sektor Tematik MI)",
    rack: "rak-b",
    jenjang: "mi",
    kategori: "tematik",
    status: "tersedia",
    format: "buku-cetak",
    tahunRange: "2020-2022",
    availableCopies: 14,
    totalCopies: 15,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDyiujE7TYOUQtFfYZTjkx209pmvu3MM1TEREt-_b62m1MrKmplsmUDyDZVpY48eR4UpZeXS8WkGZGRp5qDi05epuV4qekM1p-_w-pgqnlKUPv4pcHzOqbSqmjf1UK_e1WcHv-tVy2HMIVp_lP2xOjFRZZud1dwNJ4IJIjPVrSK2JXlOfmxa4X9Z-Rd55kdPXVnz1K4gtEbrxYEaLD7LNLlyVEfdWIr-rTz1jL_Y6LNIRhuSsaih-nq",
  },
  {
    id: "3",
    title: "Sirah Nabawiyah: Perjalanan Hidup Rasulullah SAW",
    callNumber: "BK-SRH-0331",
    author: "Syaikh Shafiyyurrahman Al-Mubarakfuri",
    publisher: "Pustaka Al-Kautsar",
    year: "Klasik",
    synopsis: "Kisah terlengkap jejak perjuangan Rasulullah SAW dari masa jahiliyah, kenabian, hijrah ke Madinah hingga Fathu Makkah pemenang Rabithah Alam Islami.",
    badgeLabel: "Sejarah Islam & Karakter",
    location: "📍 Rak A3 - Baris Ke-1 (Koleksi Tarikh Islam)",
    rack: "rak-a",
    jenjang: "umum",
    kategori: "sastra",
    status: "tersedia",
    format: "kitab",
    tahunRange: "klasik",
    availableCopies: 8,
    totalCopies: 10,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuANe7IWzJO30PTQCpOvfbegYBIVRkCsVbZEPw3um1n7nsx_76ds8-Dz_6zwR1JonMEDZJE8WW-8GoG-dBhf_aC0tthUFsN9Dz7aP4J6N4A7EjnCuuwKYcVYwe7kWsZO-6NFb55qYv6LF_6t2LtJ5uPOwxGmE4KuNHtt_sBe-6OCxW1RRXAY_-nLg_aLgMHpJxY7RmF4atTviTW0q7OGGbEXaEHQekTTJ4ddXXOMOfZshs2crAxR0uKq",
  },
  {
    id: "4",
    title: "IPA Terpadu MTs Kelas VIII",
    callNumber: "BK-IPA-0098",
    author: "Prof. Bambang H., M.Si",
    publisher: "Penerbit Erlangga",
    year: "2023",
    synopsis: "Materi sains fisika, kimia dan biologi terpadu mencakup gerak benda, sistem pencernaan, zat aditif, dan tekanan zat dengan pendekatan islami.",
    badgeLabel: "MTs • Sains & Eksak",
    location: "📍 Rak C1 - Baris Ke-3 (Sains MTs)",
    rack: "rak-c",
    jenjang: "mts",
    kategori: "sains",
    status: "tersedia",
    format: "buku-cetak",
    tahunRange: "2023-2024",
    availableCopies: 3,
    totalCopies: 8,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBzoMat30geH75XUE4Ohh_tOF86Nxx9AeQAmTDuSLMcbt-NlQvcfO_7wr7C3pYtA-6Jwpeu3_I6gTDGAwEiH-CrJphIsXfkSHQ3Q8TqCLg40uNWIOt3dixARf0Gqvr9Q8I81l2ZEw_F70QxoomItdXiBKkYvG5fQ3MDzH8ZvlSbQWIpw1PL5TFsQ69QzE0EJ_TqB8kkq_BhUg738cRNCbQu3fjc8JCgq-_3zRu24IxtM1tfN_ATlEF3",
  },
  {
    id: "5",
    title: "Kamus Al-Munawwir Arab - Indonesia Terlengkap",
    callNumber: "BK-BHS-0012",
    author: "KH. Ahmad Warson Munawwir",
    publisher: "Pustaka Progressif",
    year: "Klasik",
    synopsis: "Kamus terlengkap bahasa Arab ke bahasa Indonesia rujukan pesantren dan madrasah seluruh nusantara oleh KH. Ahmad Warson Munawwir.",
    badgeLabel: "Kamus & Referensi Khusus",
    location: "📍 Rak E2 (Koleksi Khusus Referensi)",
    rack: "rak-e",
    jenjang: "umum",
    kategori: "bahasa",
    status: "dipinjam",
    format: "referensi",
    tahunRange: "klasik",
    availableCopies: 0,
    totalCopies: 5,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuCLGlckvrRB1Ffeau4byt1X5vPHcgQ8UTMFlO73Dl27vhb0dGeCN0DUWBpeuA-WvGRa3bszUapGeKDfe6BlT5EJouAF5Im_5orzVb4NP35cZ5bpOq1_-nFTYyQnJRvQGo8HfIhNk9w2B2bAOuEdZoXALqaMiwT_lIUoMRcNjkgfK6ZW6zXrxDcKDA1450Y0higwJDNJRfkJUsgOUtEvxZjD4MLXjt1CliFOksG8JFXGW0ca8kRjV3fG",
    returnEstimate: "28 Okt 2024",
  },
  {
    id: "6",
    title: "Kisah 25 Nabi & Rasul Bergambar untuk MI",
    callNumber: "BK-CRT-0211",
    author: "Abu Hanifah Rahman",
    publisher: "Gema Insani Press",
    year: "2021",
    synopsis: "Kisah inspiratif para anbiya dengan ilustrasi penuh warna, bahasa ramah santri cilik MI untuk menanamkan akhlak dan keteladanan mulia.",
    badgeLabel: "MI • Cerita Santri Cilik",
    location: "📍 Rak D1 - Baris Ke-2 (Pojok Baca Santri Cilik)",
    rack: "rak-d",
    jenjang: "mi",
    kategori: "sastra",
    status: "tersedia",
    format: "cerita",
    tahunRange: "2020-2022",
    availableCopies: 5,
    totalCopies: 6,
    coverUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEbHAdSJE4RP_0lWsusv4ojY8R5vu_QdgLKWRS7o6oxRhUT5EeZZTkVYtHC-9M-jOYVljteVRWznUjmoIwvzx7BmTRiAn0FLmiNojfzenbYgatC1dKLREbUxzieRzab3FZSRoPlGRDCn0yGb2SXNDGAmSt3wmvwMTi99n90Kw-U1Ls5ejkz5jAV5VcHfoas1b2M7Fqnm0YR1XmoHmGasksugug8Golw2WgaUo1FP1lrS6-3j60MACY",
  },
]

export const ZONE_INFO_DATA: Record<string, ZoneInfo> = {
  A: {
    badge: "A",
    title: "Zona Rak A: Keagamaan, Kitab Turats & Fiqih Madrasah",
    shortTitle: "Kitab Turats & Fiqih Islam",
    fillRate: "95% Terisi",
    capacity: "800 Buku (95% Terisi / ~760 Buku Aktif)",
    target: "Santri MI (Tinggi), MTs & Dewan Asatidz",
    categories: "Fiqih Syafi'i, Safinatun Naja, Aqidah Akhlak, Tafsir & Al-Qur'an Hadis",
    rackCode: "rak-a",
    description: "Keagamaan, Fiqih, Aqidah Akhlak, Tafsir & Al-Qur'an Hadis (Kapasitas: 800 buku)",
    locationNote: "Lorong Utama Sebelah Barat",
  },
  B: {
    badge: "B",
    title: "Zona Rak B: Buku Tematik Kurikulum Merdeka MI (Kelas 1 - 6)",
    shortTitle: "Buku Tematik MI (Kelas 1 - 6)",
    fillRate: "90% Terisi",
    capacity: "600 Buku (90% Terisi / ~540 Buku Aktif)",
    target: "Siswa MI Kelas 1 sampai Kelas 6",
    categories: "Buku Tematik 1 - 8, Bahasa Indonesia MI, Matematika Dasar, PPKn",
    rackCode: "rak-b",
    description: "Kurikulum Merdeka MI, Tema 1 - 8, Buku Aktivitas Siswa (Kapasitas: 600 buku)",
    locationNote: "Lorong Tengah Sektor MI",
  },
  C: {
    badge: "C",
    title: "Zona Rak C: Sains, Matematika, IPA & IPS Terpadu MTs",
    shortTitle: "Sains, MTs Eksak & IPS",
    fillRate: "85% Terisi",
    capacity: "550 Buku (85% Terisi / ~467 Buku Aktif)",
    target: "Siswa MTs Kelas 7, 8, dan 9",
    categories: "Fisika & Biologi Terpadu, Matematika MTs, IPS Geografi & Sejarah, TIK/Informatika",
    rackCode: "rak-c",
    description: "Matematika, IPA Terpadu, Informatika MTs (Kapasitas: 550 buku)",
    locationNote: "Lorong Timur Sektor MTs",
  },
  D: {
    badge: "D",
    title: "Zona Rak D: Cerita 25 Nabi, Sirah Nabawiyah & Sastra Islami",
    shortTitle: "Cerita 25 Nabi & Sastra Islami",
    fillRate: "92% Terisi",
    capacity: "450 Buku (92% Terisi / ~414 Buku Aktif)",
    target: "Santri Cilik MI, Remaja MTs & Pengayaan Umum",
    categories: "Kisah Para Anbiya, Khulafaur Rasyidin, Novel Religi & Antologi Cerpen Santri",
    rackCode: "rak-d",
    description: "Sirah Nabawiyah, Kisah Sahabat & Cerpen Santri (Kapasitas: 450 buku)",
    locationNote: "Pojok Literasi & Karpet Baca",
  },
  E: {
    badge: "E",
    title: "Zona Rak E: Kamus Bahasa Arab & Inggris, Ensiklopedia Sains",
    shortTitle: "Kamus Bahasa & Ensiklopedia",
    fillRate: "Referensi",
    capacity: "300 Buku & Majalah Koleksi Khusus Referensi Meja",
    target: "Semua Santri & Dewan Guru (Baca di Tempat)",
    categories: "Kamus Al-Munawwir, Ensiklopedia Mukjizat Ilmiah Al-Qur'an, Majalah Literasi Santri",
    rackCode: "rak-e",
    description: "Kamus Arab-Indo, Oxford, Ensiklopedia Sains & Majalah Santri",
    locationNote: "Meja Referensi Baca di Tempat",
  },
}
