import { BookItem, SpreadsheetPreviewItem } from "../types/books.types";

export const INITIAL_BOOKS: BookItem[] = [
  {
    id: "book-1",
    code: "BK-AGM-0182",
    isbn: "978-602-123",
    title: "Fiqih Ibadah Praktis MTs",
    author: "Drs. H. Ahmad Muhaimin",
    publisher: "Kemenag RI",
    publicationYear: 2023,
    categories: ["Fiqih", "Syariah"],
    level: "MTs",
    shelfId: "Rak A1",
    shelfName: "Rak A1 (Agama)",
    pages: "214 hlm",
    language: "Indonesia",
    synopsis:
      "Buku panduan kaidah dasar ushul fiqih yang disusun terstruktur sesuai kurikulum madrasah terpadu untuk pemula.",
    status: "active",
    totalCopies: 15,
    availableCopies: 14,
    borrowedCopies: 1,
    copies: [
      {
        id: "cp-1",
        barcode: "BC-0182-01",
        rfidTag: "RFID-A1",
        shelfRow: "Rak A1 - Baris 2",
        status: "AVAILABLE",
        condition: "Sangat Baik",
      },
      {
        id: "cp-2",
        barcode: "BC-0182-02",
        rfidTag: "RFID-A2",
        shelfRow: "Rak A1 - Baris 2",
        status: "BORROWED",
        borrowerName: "Ahmad R. (MTs 8B)",
        condition: "Baik",
      },
      {
        id: "cp-3",
        barcode: "BC-0182-03",
        rfidTag: "RFID-A3",
        shelfRow: "Rak A1 - Baris 2",
        status: "AVAILABLE",
        condition: "Sangat Baik",
      },
    ],
  },
  {
    id: "book-2",
    code: "BK-TMT-0419",
    isbn: "978-602-456",
    title: "Tematik Terpadu 5B: Udara Bersih",
    author: "Tim Penulis Kemendikbud",
    publisher: "Balai Pustaka",
    publicationYear: 2022,
    categories: ["Tematik", "MI"],
    level: "MI",
    shelfId: "Rak B1",
    shelfName: "Rak B1 (Tematik)",
    pages: "186 hlm",
    language: "Indonesia",
    synopsis: "Materi terpadu tematik SD/MI kelas 5 tema 2 tentang pernapasan dan lingkungan bersih.",
    status: "active",
    totalCopies: 15,
    availableCopies: 14,
    borrowedCopies: 1,
    copies: [
      {
        id: "cp-4",
        barcode: "BC-0419-01",
        rfidTag: "RFID-B1",
        shelfRow: "Rak B1 - Baris 1",
        status: "AVAILABLE",
        condition: "Sangat Baik",
      },
    ],
  },
  {
    id: "book-3",
    code: "BK-IPA-0098",
    isbn: "978-602-789",
    title: "IPA Terpadu MTs Kelas VIII",
    author: "Prof. Bambang H., M.Si",
    publisher: "Erlangga",
    publicationYear: 2023,
    categories: ["Sains", "MTs"],
    level: "MTs",
    shelfId: "Rak C1",
    shelfName: "Rak C1 (Sains)",
    pages: "312 hlm",
    language: "Indonesia",
    synopsis: "Fisika dan biologi terintegrasi dengan contoh praktikum ilmiah madrasah.",
    status: "active",
    totalCopies: 8,
    availableCopies: 8,
    borrowedCopies: 0,
    copies: [
      {
        id: "cp-5",
        barcode: "BC-0098-01",
        rfidTag: "RFID-C1",
        shelfRow: "Rak C1 - Baris 3",
        status: "AVAILABLE",
        condition: "Sangat Baik",
      },
    ],
  },
  {
    id: "book-4",
    code: "BK-CRT-0211",
    isbn: "978-602-333",
    title: "Kisah 25 Nabi & Rasul Bergambar",
    author: "Abu Hanifah Rahman",
    publisher: "Gema Insani Press",
    publicationYear: 2021,
    categories: ["Sastra", "Cerita Islam"],
    level: "Umum",
    shelfId: "Rak D1",
    shelfName: "Rak D1 (Cerita)",
    pages: "260 hlm",
    language: "Indonesia",
    synopsis: "Kumpulan kisah inspiratif 25 Nabi dan Rasul dilengkapi ilustrasi edukatif ramah anak.",
    status: "inactive",
    totalCopies: 5,
    availableCopies: 5,
    borrowedCopies: 0,
    copies: [
      {
        id: "cp-6",
        barcode: "BC-0211-01",
        rfidTag: "RFID-D1",
        shelfRow: "Rak D1 - Baris 1",
        status: "AVAILABLE",
        condition: "Baik",
      },
    ],
  },
  {
    id: "book-5",
    code: "BK-BHS-0012",
    isbn: "978-979-456",
    title: "Kamus Al-Munawwir Arab-Indo",
    author: "KH. Ahmad Warson Munawwir",
    publisher: "Progressif",
    publicationYear: 2020,
    categories: ["Bahasa", "Kamus"],
    level: "MTs",
    shelfId: "Rak C2",
    shelfName: "Rak C2 (Bahasa)",
    pages: "1634 hlm",
    language: "Arab",
    synopsis: "Kamus referensi terlengkap kosakata bahasa Arab-Indonesia untuk santri dan akademisi.",
    status: "active",
    totalCopies: 3,
    availableCopies: 3,
    borrowedCopies: 0,
    copies: [
      {
        id: "cp-7",
        barcode: "BC-0012-01",
        rfidTag: "RFID-C2",
        shelfRow: "Rak C2 - Baris 1",
        status: "AVAILABLE",
        condition: "Sangat Baik",
      },
    ],
  },
];

export const SHELF_OPTIONS = [
  { id: "Rak A1", name: "Rak A1 - Koleksi Agama & Fiqih", label: "Rak A1 (Agama)" },
  { id: "Rak B1", name: "Rak B1 - Tematik Madrasah Ibtidaiyah", label: "Rak B1 (Tematik)" },
  { id: "Rak C1", name: "Rak C1 - Sains & Eksakta MTs", label: "Rak C1 (Sains)" },
  { id: "Rak C2", name: "Rak C2 - Bahasa & Kamus Rujukan", label: "Rak C2 (Bahasa)" },
  { id: "Rak D1", name: "Rak D1 - Sastra & Cerita Islami", label: "Rak D1 (Cerita)" },
];

export const CATEGORY_TAG_OPTIONS = [
  "Fiqih",
  "Syariah",
  "Aqidah & Akhlak",
  "Tematik MI",
  "Sains MTs",
  "Kamus & Bahasa",
  "Sastra",
  "Cerita Islam",
];

export const SAMPLE_SPREADSHEET_PREVIEW: SpreadsheetPreviewItem[] = [
  {
    code: "BK-AGM-0183",
    title: "Tafsir Jalalain Juz Amma",
    isbn: "978-602-9981",
    author: "Imam Jalaluddin",
    shelf: "Rak A1",
    isValid: true,
  },
  {
    code: "BK-TMT-0420",
    title: "Tematik Terpadu 5C: Makanan Sehat",
    isbn: "978-602-4562",
    author: "Kemendikbud",
    shelf: "Rak B1",
    isValid: true,
  },
  {
    code: "BK-EXT-0001",
    title: "Ensiklopedia Sains Modern",
    isbn: "978-602-0019",
    author: "Dr. Hendra S.",
    shelf: "Rak X9 (Unknown)",
    isValid: false,
    notes: "Penomoran rak belum terdaftar, otomatis dialokasikan ke Rak Sementara.",
  },
];
