import { MasterItem, MasterMetric, MasterTabConfig } from "../types/master-data.types";

export const MASTER_METRICS_DATA: MasterMetric[] = [
  {
    id: "metric-kategori",
    title: "Kategori & Klasifikasi",
    value: "18",
    unit: "Sub-Bidang",
    badgeText: "DDC & Kemenag",
    badgeVariant: "emerald",
    description: "Termasuk kitab kuning & silabus madrasah",
    icon: "tag",
  },
  {
    id: "metric-rak",
    title: "Kapasitas Rak Fisik",
    value: "4.850",
    unit: "Eksemplar",
    badgeText: "82% Terisi",
    badgeVariant: "blue",
    description: "Terdistribusi pada rak utama A s/d D",
    icon: "layers",
  },
  {
    id: "metric-penerbit",
    title: "Mitra Penerbit",
    value: "42",
    unit: "Rekanan",
    badgeText: "100% Aktif",
    badgeVariant: "amber",
    description: "Kemendikbud, Balai Pustaka, Erlangga, dll",
    icon: "building",
  },
  {
    id: "metric-rombel",
    title: "Rombel MI & MTs",
    value: "24",
    unit: "Rombel",
    badgeText: "742 Anggota",
    badgeVariant: "purple",
    description: "Kelas 1-6 MI & Kelas 7-9 MTs Terdaftar",
    icon: "users",
  },
];

export const MASTER_TAB_CONFIGS: Record<string, MasterTabConfig> = {
  kategori: {
    key: "kategori",
    label: "Kategori Buku",
    singularLabel: "Kategori & Klasifikasi Buku",
    codePrefix: "KTG",
    codePlaceholder: "cth: KTG-007",
    namePlaceholder: "cth: Fiqih & Ushul Fiqih",
    descPlaceholder: "cth: Klasifikasi hukum Islam, madzhab, dan muamalah madrasah",
    relationPlaceholder: "cth: 420 Judul",
  },
  rak: {
    key: "rak",
    label: "Lokasi Rak Fisik",
    singularLabel: "Lokasi Rak Fisik",
    codePrefix: "RAK",
    codePlaceholder: "cth: RAK-E",
    namePlaceholder: "cth: Rak E: Kamus & Referensi Bahasa",
    descPlaceholder: "cth: Lorong Utara Lt. 2 (Koleksi Rujukan & Kamus Santri)",
    relationPlaceholder: "cth: Kapasitas 1.000 Eks (820 Terisi)",
  },
  penerbit: {
    key: "penerbit",
    label: "Mitra Penerbit",
    singularLabel: "Mitra Penerbit",
    codePrefix: "PBT",
    codePlaceholder: "cth: PBT-007",
    namePlaceholder: "cth: Toha Putra Semarang",
    descPlaceholder: "cth: Penerbitan kitab kuning turats & naskah pondok pesantren",
    relationPlaceholder: "cth: 180 Judul Terdaftar",
  },
  kelas: {
    key: "kelas",
    label: "Tingkat & Rombel Kelas",
    singularLabel: "Tingkat & Rombel Kelas",
    codePrefix: "KLS",
    codePlaceholder: "cth: KLS-MI-1A",
    namePlaceholder: "cth: Kelas 1 MI Ar-Rasyid (A & B)",
    descPlaceholder: "cth: Tingkat dasar MI semester ganjil ruang Abu Bakar Ash-Shiddiq",
    relationPlaceholder: "cth: 62 Siswa Anggota",
  },
};

export const INITIAL_MASTER_ITEMS: MasterItem[] = [
  // 1. Kategori Buku
  {
    id: "ktg-1",
    code: "KTG-001",
    name: "Fiqih & Ibadah Praktis",
    description: "Klasifikasi hukum ibadah, muamalah, rukun Islam & fiqih madrasah",
    relation: "420 Judul",
    status: "Aktif",
    type: "kategori",
  },
  {
    id: "ktg-2",
    code: "KTG-002",
    name: "Tematik Kurikulum MI",
    description: "Buku tematik terintegrasi kemenag & kemendikbud kelas 1-6 MI",
    relation: "860 Judul",
    status: "Aktif",
    type: "kategori",
  },
  {
    id: "ktg-3",
    code: "KTG-003",
    name: "Bahasa & Sastra Arab-Inggris",
    description: "Gramatikal nahwu-shorof dasar, kamus istilah santri, & percakapan dwibahasa",
    relation: "310 Judul",
    status: "Aktif",
    type: "kategori",
  },
  {
    id: "ktg-4",
    code: "KTG-004",
    name: "Sains & Matematika Terpadu",
    description: "Eksperimen IPA dasar MI, matematika kontekstual & modul olimpiade MTs",
    relation: "540 Judul",
    status: "Aktif",
    type: "kategori",
  },
  {
    id: "ktg-5",
    code: "KTG-005",
    name: "Sejarah Kebudayaan Islam (SKI)",
    description: "Khulafaur Rasyidin, peradaban Islam nusantara & biografi wali songo",
    relation: "290 Judul",
    status: "Aktif",
    type: "kategori",
  },
  {
    id: "ktg-6",
    code: "KTG-006",
    name: "Akhlak, Fabel & Kisah Nabi",
    description: "Buku pembiasaan budi pekerti, kisah 25 nabi & literasi fabel Islami anak",
    relation: "380 Judul",
    status: "Aktif",
    type: "kategori",
  },

  // 2. Lokasi Rak Fisik
  {
    id: "rak-1",
    code: "RAK-A",
    name: "Rak A: Kitab Turats & Fiqih Islam",
    description: "Lorong Barat Lt. 2 (Koleksi Fiqih, Tafsir Al-Qur'an, Hadits, & Risalah Akhlak)",
    relation: "Kapasitas 1.200 Eks (950 Terisi)",
    status: "Aktif",
    type: "rak",
  },
  {
    id: "rak-2",
    code: "RAK-B",
    name: "Rak B: Buku Tematik Kurikulum MI",
    description: "Lorong Tengah Utara Lt. 2 (Koleksi Tematik Terpadu MI Kelas 1 s/d 6)",
    relation: "Kapasitas 1.500 Eks (1.320 Terisi)",
    status: "Aktif",
    type: "rak",
  },
  {
    id: "rak-3",
    code: "RAK-C",
    name: "Rak C: Sains, Matematika & MTs Eksak",
    description: "Lorong Tengah Selatan Lt. 2 (Modul Eksperimen IPA, Matematika Kontekstual, IPS)",
    relation: "Kapasitas 1.100 Eks (880 Terisi)",
    status: "Aktif",
    type: "rak",
  },
  {
    id: "rak-4",
    code: "RAK-D",
    name: "Rak D: Cerita Islami, Fabel & Karakter",
    description: "Lorong Timur Lt. 2 (Kisah 25 Nabi, Teladan Sahabat, Fabel Anak Bergambar)",
    relation: "Kapasitas 1.050 Eks (920 Terisi)",
    status: "Aktif",
    type: "rak",
  },

  // 3. Mitra Penerbit
  {
    id: "pbt-1",
    code: "PBT-001",
    name: "Balai Pustaka Indonesia",
    description: "Sastra nusantara, sastra klasik melayu, cerita rakyat & fabel anak",
    relation: "210 Judul",
    status: "Aktif",
    type: "penerbit",
  },
  {
    id: "pbt-2",
    code: "PBT-002",
    name: "Kementerian Agama RI (Kemenag)",
    description: "Buku ajar kurikulum madrasah MI & MTs, buku fiqih, ski, akidah akhlak",
    relation: "480 Judul",
    status: "Aktif",
    type: "penerbit",
  },
  {
    id: "pbt-3",
    code: "PBT-003",
    name: "Kemendikbudristek RI",
    description: "Buku pegangan kurikulum merdeka MI & MTs terstandarisasi nasional",
    relation: "520 Judul",
    status: "Aktif",
    type: "penerbit",
  },
  {
    id: "pbt-4",
    code: "PBT-004",
    name: "Penerbit Erlangga",
    description: "Buku sains interaktif, modul olimpiade madrasah, matematika kontekstual",
    relation: "180 Judul",
    status: "Aktif",
    type: "penerbit",
  },
  {
    id: "pbt-5",
    code: "PBT-005",
    name: "Toha Putra Semarang",
    description: "Kitab gundul turats, matan fiqih klasik, nahwu shorof pesantren",
    relation: "150 Judul",
    status: "Aktif",
    type: "penerbit",
  },
  {
    id: "pbt-6",
    code: "PBT-006",
    name: "Mizan Publika / DAR! Mizan",
    description: "Komik adab anak sholeh, novel inspiratif santri cilik, serial islami",
    relation: "140 Judul",
    status: "Aktif",
    type: "penerbit",
  },

  // 4. Tingkat & Rombel Kelas
  {
    id: "kls-1",
    code: "KLS-MI-1",
    name: "Kelas 1 MI Ar-Rasyid (A & B)",
    description: "Tingkat dasar MI semester ganjil ruang Abu Bakar Ash-Shiddiq",
    relation: "62 Siswa",
    status: "Aktif",
    type: "kelas",
  },
  {
    id: "kls-2",
    code: "KLS-MI-2",
    name: "Kelas 2 MI Ar-Rasyid (A & B)",
    description: "Tingkat dasar MI semester ganjil ruang Umar bin Khattab",
    relation: "64 Siswa",
    status: "Aktif",
    type: "kelas",
  },
  {
    id: "kls-3",
    code: "KLS-MI-6",
    name: "Kelas 6 MI Ar-Rasyid (A, B & C)",
    description: "Tingkat akhir persiapan ujian madrasah ibtidaiyah ruang Utsman bin Affan",
    relation: "88 Siswa",
    status: "Aktif",
    type: "kelas",
  },
  {
    id: "kls-4",
    code: "KLS-MTS-7",
    name: "Kelas 7 MTs Ar-Rasyid (A, B & C)",
    description: "Jenjang awal madrasah tsanawiyah santri baru ruang Ali bin Abi Thalib",
    relation: "95 Siswa",
    status: "Aktif",
    type: "kelas",
  },
  {
    id: "kls-5",
    code: "KLS-MTS-8",
    name: "Kelas 8 MTs Ar-Rasyid (A & B)",
    description: "Jenjang madya sains & riset tsanawiyah ruang Bilal bin Rabah",
    relation: "72 Siswa",
    status: "Aktif",
    type: "kelas",
  },
  {
    id: "kls-6",
    code: "KLS-MTS-9",
    name: "Kelas 9 MTs Ar-Rasyid (A, B & C)",
    description: "Jenjang akhir tsanawiyah kelulusan santri ruang Khalid bin Walid",
    relation: "92 Siswa",
    status: "Aktif",
    type: "kelas",
  },
];
